# HMDM Docker Compose Configuration

services:

  # Using external Neon database - no local PostgreSQL or certbot needed

  hmdm:
    image: headwindmdm/hmdm:0.1.5
    ports:
      # Using HTTP for local testing - changed external port to avoid conflict
      - 8081:8080
      - 31000:31000
    volumes:
      - ./volumes/work:/usr/local/tomcat/work
      - ./volumes/letsencrypt:/etc/letsencrypt
      - ./volumes/hmdm-config:/usr/local/tomcat/conf/Catalina/localhost
      - ./tomcat_conf/server.xml:/usr/local/tomcat/conf/server.xml
    environment:
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
      SQL_USER: ${SQL_USER}
      SQL_BASE: ${SQL_BASE}
      SQL_PASS: ${SQL_PASS}
      BASE_DOMAIN: ${BASE_DOMAIN}
      LOCAL_IP: ${LOCAL_IP}
      PROTOCOL: ${PROTOCOL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SHARED_SECRET: ${SHARED_SECRET}
      HMDM_VARIANT: ${HMDM_VARIANT}
      DOWNLOAD_CREDENTIALS: ${DOWNLOAD_CREDENTIALS}
      HMDM_URL: ${HMDM_URL}
      CLIENT_VERSION: ${CLIENT_VERSION}
      FORCE_RECONFIGURE: ${FORCE_RECONFIGURE}
      LIQUIBASE_SKIP_MIGRATION: ${LIQUIBASE_SKIP_MIGRATION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/rest/public/info"]
      interval: 30s
      timeout: 10s
      retries: 3

